on:
  release:
    types: [created]

jobs:
  release:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@master
      - run: cargo build --release
      - name: Generate CounterSetup.exe
        run: makensis counter.sni
      - name: Upload artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: CounterSetup.exe